# Generated by Django 5.0.6 on 2024-10-29 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_periodmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodmodel',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='app.staffmodel'),
        ),
        migrations.AddField(
            model_name='periodmodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='app.subjectmodel'),
        ),
    ]
